//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class iiWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal iiWeb() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.iiWeb", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 yy-mm-dd 的本地化字符串。
        /// </summary>
        internal static string AltDateFormat {
            get {
                return ResourceManager.GetString("AltDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @ 的本地化字符串。
        /// </summary>
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        internal static string AuthorityCaption {
            get {
                return ResourceManager.GetString("AuthorityCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限管理 的本地化字符串。
        /// </summary>
        internal static string AuthorityDetailTitle {
            get {
                return ResourceManager.GetString("AuthorityDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法参数！ 的本地化字符串。
        /// </summary>
        internal static string BadParameterErrorMessage {
            get {
                return ResourceManager.GetString("BadParameterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string CheckAllCaption {
            get {
                return ResourceManager.GetString("CheckAllCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置 的本地化字符串。
        /// </summary>
        internal static string CIDCaption {
            get {
                return ResourceManager.GetString("CIDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置详情 的本地化字符串。
        /// </summary>
        internal static string ConfigDetailTitle {
            get {
                return ResourceManager.GetString("ConfigDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置管理 的本地化字符串。
        /// </summary>
        internal static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定继续吗？ 的本地化字符串。
        /// </summary>
        internal static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        internal static string ConfirmPasswordCaption {
            get {
                return ResourceManager.GetString("ConfirmPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码和确认密码必须一致！ 的本地化字符串。
        /// </summary>
        internal static string ConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;copy; 版权所有 的本地化字符串。
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增失败！ 的本地化字符串。
        /// </summary>
        internal static string CreateErrorMessage {
            get {
                return ResourceManager.GetString("CreateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yy-mm-dd 的本地化字符串。
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败！ 的本地化字符串。
        /// </summary>
        internal static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string EditCaption {
            get {
                return ResourceManager.GetString("EditCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (无数据) 的本地化字符串。
        /// </summary>
        internal static string EmptyData {
            get {
                return ResourceManager.GetString("EmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据已存在！ 的本地化字符串。
        /// </summary>
        internal static string ExistedErrorMessage {
            get {
                return ResourceManager.GetString("ExistedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您好， 的本地化字符串。
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  (角色继承) 的本地化字符串。
        /// </summary>
        internal static string Inherited {
            get {
                return ResourceManager.GetString("Inherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数无效！ 的本地化字符串。
        /// </summary>
        internal static string InvalidParameterErrorMessage {
            get {
                return ResourceManager.GetString("InvalidParameterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        internal static string KeyCaption {
            get {
                return ResourceManager.GetString("KeyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号无效或密码错误！ 的本地化字符串。
        /// </summary>
        internal static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string NameCaption {
            get {
                return ResourceManager.GetString("NameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选取任何项！ 的本地化字符串。
        /// </summary>
        internal static string NotSelectMessage {
            get {
                return ResourceManager.GetString("NotSelectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统名。[FavNet.cn 专业IT技术服务]提供技术支持 [Plusii 您的企业附加值]旗下品牌 的本地化字符串。
        /// </summary>
        internal static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统名,FavNet.cn,专业IT技术服务,Plusii,您的企业附加值 的本地化字符串。
        /// </summary>
        internal static string PageKeywords {
            get {
                return ResourceManager.GetString("PageKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string PasswordCaption {
            get {
                return ResourceManager.GetString("PasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功！请牢记您的新密码 的本地化字符串。
        /// </summary>
        internal static string PasswordChangedMessage {
            get {
                return ResourceManager.GetString("PasswordChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码 的本地化字符串。
        /// </summary>
        internal static string PasswordTitle {
            get {
                return ResourceManager.GetString("PasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered by &lt;a title=&quot;专业IT技术服务&quot; href=&quot;http://www.favnet.cn&quot; target=&quot;_blank&quot;&gt;Plusii&lt;/a&gt; 的本地化字符串。
        /// </summary>
        internal static string Powered {
            get {
                return ResourceManager.GetString("Powered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (属性1) 的本地化字符串。
        /// </summary>
        internal static string Property1Caption {
            get {
                return ResourceManager.GetString("Property1Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string RemarkCaption {
            get {
                return ResourceManager.GetString("RemarkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出报表 的本地化字符串。
        /// </summary>
        internal static string ReportButton {
            get {
                return ResourceManager.GetString("ReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写必要项！ 的本地化字符串。
        /// </summary>
        internal static string RequiredFieldValidationErrorMessage {
            get {
                return ResourceManager.GetString("RequiredFieldValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string RoleCaption {
            get {
                return ResourceManager.GetString("RoleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 iiWeb框架构建系统 的本地化字符串。
        /// </summary>
        internal static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工号 的本地化字符串。
        /// </summary>
        internal static string UIDCaption {
            get {
                return ResourceManager.GetString("UIDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败！ 的本地化字符串。
        /// </summary>
        internal static string UpdateErrorMessage {
            get {
                return ResourceManager.GetString("UpdateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户详情 的本地化字符串。
        /// </summary>
        internal static string UserDetailTitle {
            get {
                return ResourceManager.GetString("UserDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        internal static string UserIDCaption {
            get {
                return ResourceManager.GetString("UserIDCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        internal static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请点击菜单开始 ... 的本地化字符串。
        /// </summary>
        internal static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用 的本地化字符串。
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
    }
}
